# 24787 Recitation1 : Installation and basics of Numpy

$\hspace{5mm}$Rishikesh Magar - rmagar@andrew.cmu.edu

## Installation

We will be using Jupyter notebooks for this course. Before diving into numpy, vectorization and python basics please make sure that you have python3 installed in your computer. For python installation we would prefer the anaconda distribution.

visit the webpage: https://www.anaconda.com/distribution and follow the instructions. Make sure you install python3 since python 2 will no longer be supported starting Jan 2020 

# NUMPY basics

- What is NumPy?

## Download and Installation

If you have installed python correctly. Numpy should perhaps come with it. If numpy is not installed please follow instructions at https://scipy.org/install.html

# Lists

In [1]:
# Lists - can store anything

list_of_things = ['AI and ML for Engineers'] # initalise
list_of_things.append(24787)
list_of_things.append('CIT @ CMU')
list_of_things.append(True)

# Accessing objects
print(type(list_of_things[3]))

# Print the list
print(list_of_things)

# Create another list
another_list = ['More objects', ['List inside a list!']]

# Merge the lists
third_lists = list_of_things + another_list
print(third_lists)

# Extend list_of_things
print('\nLength before adding another_list',len(list_of_things),'\n')
list_of_things.extend(another_list)
print('Length after adding another_list',len(list_of_things),'\n')

list_of_things+=another_list
print(list_of_things)


<class 'bool'>
['AI and ML for Engineers', 24787, 'CIT @ CMU', True]
['AI and ML for Engineers', 24787, 'CIT @ CMU', True, 'More objects', ['List inside a list!']]

Length before adding another_list 4 

Length after adding another_list 6 

['AI and ML for Engineers', 24787, 'CIT @ CMU', True, 'More objects', ['List inside a list!'], 'More objects', ['List inside a list!']]


## Introductory Example: Implementing with Lists 

To know the difference between an array and a list please Google ;)

This blog also provides a good explanation : https://medium.com/backticks-tildes/list-vs-array-python-data-type-40ac4f294551

In [11]:
# Inputs
# Now that we know what a list is lets use it to do a simple calculation
theta_1 = [[2, 1, 3],
     [1, 2, 3],
     [3, 1, 2]]

x = [7, 8, 5]
theta_0 = [1, 1, 1]

# Output
y = [0, 0, 0]

# Computation of y = theta_1*x + theta_0
for i in range(len(theta_1)):
    for j in range(len(x)):
        y[i] = y[i]+theta_1[i][j] * x[j]+ (theta_0[i])

# for i in range(len(y)):
#     y[i] += b[i]
print(y)


[40, 41, 42]


In [7]:
W1 = [[1, 1, 1],
     [2, 2, 2],
     [3, 3, 3],
     [4,4,4]]
import numpy as np
W2 = np.asarray(W1) 
W2.shape

(4, 3)

### NumPy-based Vectorized Implementation

In [8]:
import numpy as np

In [14]:
W = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])
W.shape

(3, 3)

In [21]:
x = np.array([7, 8, 5])
x.shape

(3,)

In [22]:
b = np.ones(3)
b

array([1., 1., 1.])

In [23]:
W.dot(x)

array([20, 40, 60])

In [24]:
W.dot(x) + b

array([21., 41., 61.])

## Multi-Dimensional Arrays

In [25]:
T = np.random.random((2,3,4))
T

array([[[0.96351691, 0.77375275, 0.28687746, 0.30528653],
        [0.92791877, 0.56225443, 0.55508502, 0.07712794],
        [0.21012592, 0.46030801, 0.27883737, 0.44634651]],

       [[0.21154662, 0.54855307, 0.4846036 , 0.12297319],
        [0.85128901, 0.06431261, 0.0116154 , 0.5376059 ],
        [0.61372249, 0.67358703, 0.57263255, 0.13152588]]])

In [26]:
W = T[1]
W.shape, W.dtype

((3, 4), dtype('float64'))

In [30]:
X = np.full((4,3), 11785, dtype=np.int32) # prints out the same in all dimension
X.shape, X.dtype

((4, 3), dtype('int32'))

In [31]:
W.dot(X)

array([[16118.06729937, 16118.06729937, 16118.06729937],
       [17262.93811414, 17262.93811414, 17262.93811414],
       [23469.44974789, 23469.44974789, 23469.44974789]])

In [32]:
X2 = np.zeros(X.shape)

np.array_equal(W.dot(X2), np.zeros((3,3)))

True

## Basic Element-wise Operations

In [33]:
y = np.arange(10)
y, np.array(range(10))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [34]:
y == np.array(range(10))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [35]:
y + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
y * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
(y + 1)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [38]:
y + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
y / (y + 1)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [40]:
np.sqrt(y**2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
y.min(), y.max(), y.std(), y.sum()

(0, 9, 2.8722813232690143, 45)

## Indexing NumPy Arrays

In [50]:
np.save('tensor.npy', np.arange(2 * 4 * 4).reshape(2, 4,4))

In [51]:
T = np.load('tensor.npy')
T,  T.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]]), (2, 4, 4))

In [52]:
T[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
T[1,0,0]  # more efficient version of T[1][0][0]

16

In [57]:
T[0,0:4,0:2] # selecting the 

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [58]:
(T % 10) == 0

array([[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [ True, False, False, False],
        [False, False, False, False],
        [False, False,  True, False]]])

In [68]:
T[(T % 10) == 0] 

array([ 0, 10, 20, 30])

## Example: Masking and Clipping

In [77]:
W = np.random.randint(0, 8, (4, 4)) # 8 i sthe limit of the maximum values 
W

array([[0, 5, 7, 7],
       [4, 5, 5, 3],
       [7, 6, 2, 3],
       [7, 0, 2, 6]])

In [78]:
mask = np.ones_like(W)
mask[1] = 0
mask

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [79]:
W * mask

array([[0, 5, 7, 7],
       [0, 0, 0, 0],
       [7, 6, 2, 3],
       [7, 0, 2, 6]])

In [80]:
W > 5

array([[False, False,  True,  True],
       [False, False, False, False],
       [ True,  True, False, False],
       [ True, False, False,  True]])

In [81]:
W2 = W
W2[W2 > 5] = 5
W2 # beautiful way of comparing 

array([[0, 5, 5, 5],
       [4, 5, 5, 3],
       [5, 5, 2, 3],
       [5, 0, 2, 5]])

In [82]:
np.minimum(W, 5)

array([[0, 5, 5, 5],
       [4, 5, 5, 3],
       [5, 5, 2, 3],
       [5, 0, 2, 5]])

## Computation Along Axes

In [83]:
A = np.random.random((3,3))
A

array([[0.07525689, 0.91572862, 0.13968996],
       [0.66676866, 0.1500341 , 0.88076877],
       [0.65962014, 0.95427169, 0.44155668]])

In [84]:
A.sum()

4.883695514926788

In [85]:
A.sum(axis=0) # column wise # col1 # col2 #col3

array([1.40164568, 2.02003442, 1.46201541])

In [87]:
A.sum(axis=1) # row 1 

array([1.13067547, 1.69757153, 2.05544852])

In [88]:
A.max(axis=0), A.argmax(axis=0)

(array([0.66676866, 0.95427169, 0.88076877]), array([1, 2, 1], dtype=int64))

## Combining Arrays: Stacking & Concatenation

In [89]:
a = np.full(5, 1)
b = np.full(5, 2)
c = np.full(5, 3)
a, b, c

(array([1, 1, 1, 1, 1]), array([2, 2, 2, 2, 2]), array([3, 3, 3, 3, 3]))

Stacking creates a new axis. It joins the supplied arrays, which must have the same shape, along that axis.
Indexing a single element from that axis returns the appropriate input array.

In [92]:
B = np.stack([a, b, c], axis=1)
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (5, 3))

In [93]:
B[:,1]

array([2, 2, 2, 2, 2])

Concatenating arrays joins them along an *existing* aixs.

In [96]:
C = np.concatenate([B+100, B+200], axis=1
                  )
C

array([[101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203]])

## Transposing and Reshaping

In [97]:
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (5, 3))

In [98]:
BT = B.T
BT, BT.shape

(array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]]), (3, 5))

In [100]:
BR = B.reshape(3, 5)
BR, BR.shape # it goes row wise 

(array([[1, 2, 3, 1, 2],
        [3, 1, 2, 3, 1],
        [2, 3, 1, 2, 3]]), (3, 5))

## Broadcasting

In [101]:
A = np.random.random((8, 4))
B = np.random.random((4, 3))
A.dot(B)

array([[1.26429493, 0.24495927, 1.06725152],
       [1.75707904, 0.69843245, 1.30007419],
       [1.23546747, 0.96822035, 0.87771359],
       [1.34990525, 0.54137841, 1.13365397],
       [2.07928691, 1.24302455, 1.46951904],
       [1.88479748, 0.97378711, 1.61675636],
       [1.77314492, 0.66142923, 1.44080806],
       [1.4889392 , 0.64157103, 1.32179583]])

In [102]:
b = np.array([10, 20, 30])
A.dot(B) + b

array([[11.26429493, 20.24495927, 31.06725152],
       [11.75707904, 20.69843245, 31.30007419],
       [11.23546747, 20.96822035, 30.87771359],
       [11.34990525, 20.54137841, 31.13365397],
       [12.07928691, 21.24302455, 31.46951904],
       [11.88479748, 20.97378711, 31.61675636],
       [11.77314492, 20.66142923, 31.44080806],
       [11.4889392 , 20.64157103, 31.32179583]])

Arrays must have same ending dimensions to broadcast. columns??

In [110]:
#print(np.arange(12).reshape((3,4)) + 0.01 * np.arange(4))
print(np.arange(8).reshape((2,4)) + 0.01 * np.arange(16).reshape((2,2,4))) # it either has to be the same shape or a single row/column array 
#print(np.arange(6).reshape((3,1,2)) + 0.01 * np.arange(18).reshape((3,3,2)))

[[[0.   1.01 2.02 3.03]
  [4.04 5.05 6.06 7.07]]

 [[0.08 1.09 2.1  3.11]
  [4.12 5.13 6.14 7.15]]]


Mismatched dimensions cause an error.

In [117]:
try:
  x = np.random.random((2,4))+np.random.random((4,4))
except ValueError as e:
  print(e)

operands could not be broadcast together with shapes (2,4) (4,4) 


## Saving and Loading

### Saving and loading a single NumPy array

In [105]:
# Save single array
x = np.random.random((5,))
print(x)

np.save('tmp.npy', x)

[0.35236696 0.2647912  0.55923498 0.11855071 0.96468536]


In [106]:
# Load the array
y = np.load('tmp.npy')

print(y)

[0.35236696 0.2647912  0.55923498 0.11855071 0.96468536]


### Saving and loading a dictionary of NumPy arrays

In [107]:
# Save dictionary of arrays
x1 = np.random.random((2,))
y1 = np.random.random((3,))
print(x1, y1)

np.savez('tmp.npz', x=x1, y=y1)

[0.09748973 0.11835117] [0.92185591 0.86983344 0.53393804]


In [108]:
# Load the dictionary of arrays
data = np.load('tmp.npz')

print(data['x'])
print(data['y'])

[0.09748973 0.11835117]
[0.92185591 0.86983344 0.53393804]


In [ ]:
# load csv file

### Basic python

### Numbers operators and comments

In [1]:
# This is how you comment things out 
print(type(9))
print(type(9.0))
print(type(1+3.33))

<class 'int'>
<class 'float'>
<class 'float'>


In [2]:
print(2 ** 3)
print(1+2/3)

8
1.6666666666666665


In [ ]:
decimal = 12.456435

# type casting: convert a data type
decimal = int(decimal)
print(decimal)

### Variables and strings

#### Varialbes are assigned with the variable name on the left and the value on the right of the equals sign. 
#### Variables must be assigned before they can be used.

In [3]:
days_hw_due = 5
days_hw_due = days_hw_due -1
print(days_hw_due)

4


### Boolean and condition

In [4]:
color = input ("whats your favorite color")
if color == "purple":
    print("great choice")
elif color == "pure darkness":
    print("I like how you think")
elif color == "pink":
    print("not bad")

whats your favorite colorpurple
great choice


In [5]:
# 2-8: 2 dollar ticket
# 65: 5 dollar ticket
# 10 dollar for everyone else

age = 8
if not ((age >=2 and age<=8) or age >=65):
    print("You pay 10 dollars and are not a child or senior")
else:
    print("You are a child or senior")

You are a child or senior


### Looping

In [6]:
# General Form 

#for item in iterabl_object:
    # do something with item
    
# item is a new variable that you can call it whatever
# item references the current position of out iterator wihtin the iterable

### Ranges

A range is just a slice of number line.
Ex: range (1,8) will give you integers from 1 to 7

In [ ]:
rg = range(1,10,2)
print(rg) # 2 is the step, numbers to skip

In [ ]:
print(list(rg))

Use a for loop for add up every odd number from 10 to 20 (inclusive) and store the result in the variable x.

In [7]:
x = 0
for n in range(10, 21):  #remember range is exclusive, so we have to go up to 21
    if n % 2 != 0: # % means mod
        x += n

10
15


###  Given the string "amazing", create a variable ans, which is a list containing all the letters from "amazing" but not the vowels (a,e,i,o,u) The ans shall look like ["m",'z','n','g']. Use list comprehension.

In [8]:
ans = [char for char in "amazing" if char not in "aeiou"]
print(ans)

['m', 'z', 'n', 'g']


### While Loop and using "len"

In [ ]:
numbers = [1,2,3,4]
i=0
while i < len(numbers):
    print(numbers[i])
    i+=1

### List slicing and join

In [ ]:
# some_list[start:end:step] like range but separated with colons

colors = ['red','blue','green','yellow','purple','indigo']
print(colors[:5])
print(colors[0:5])
print(colors[2:-1])
print(colors[2:])
print(colors[::2])
print(colors[::-1])
print(colors[5][::-1])

# Join (a string method)
words = ["Python","Is","Great"]
words =".".join(words)
print(words)


## Dictionaries

In [35]:
# A data structure that contains key-value pairs
# keys and values are separated by colons
# keys are almost always numnbers or strings
# note: dictionary doesnt have a specific order, unlike a list
cmu = {
    'founder': "Andrew Carnegie",
    'private school?': True,
    'acceptance rate':0.2,
     4:"number of other campuses"
}
print(cmu)
print(cmu["founder"])
# print(cmu["mascot"])

{'founder': 'Andrew Carnegie', 'private school?': True, 'acceptance rate': 0.2, 4: 'number of other campuses'}
Andrew Carnegie


#### Accessing all values in a dictionary

In [11]:
# Access value: Use .values()
for value in cmu.values():
    print(value)

Andrew Carnegie
True
0.2
number of other campuses


In [12]:
# Access key: Use .keys()
for key in cmu.keys():
    print(key)

founder
private school?
acceptance rate
4


In [13]:
# Access both: .items()
for key,value in cmu.items():
    print(key, ":", value)

founder : Andrew Carnegie
private school? : True
acceptance rate : 0.2
4 : number of other campuses


In [14]:
# Test if a key exists: Use "in"
print("founder" in cmu)
print("good food" in cmu)

True
False


In [15]:
# get: Retrieves a key in a object, and return None instead of KeyError
d = dict(a=1,b=2,c=3)
print(d.get("a"))
print(d.get("no_key"))
print(d["no_key"])

1
None


KeyError: 'no_key'

### Dictionary Methods

In [16]:
d = dict(a=1,b=2,c=3)
clone = d.copy()
print(clone)
print(clone == d)
print(clone is d)

{'a': 1, 'b': 2, 'c': 3}
True
False


### Functions

return: 

1.Exits the function 

2.Outputs whatever value is places after the return keyword

3.Need to add parenthesis after the function name

In [34]:
from random import random
def flip_coin():
    #generates random number 0-1
    r = random()
    if r > 0.5:
        return "Heads"
    else: 
        return "Tails"

flip_coin()

'Heads'

#### Function that accepts inputs (parameters vs arguments)

In [33]:
def min_max_key_in_dictionary(d):
    keys = d.keys()
    return [min(keys), max(keys)]

min_max_key_in_dictionary({1:"eat",2:"sleep",3:"drink",4:"play"})

[1, 4]

In [ ]:
# Keyworded Arguments 
# Will cover this if time permitted

## References

You can find a more complete introduction at https://docs.scipy.org/doc/numpy/user/quickstart.html